# SPDX-FileCopyrightText: 2023 Julian-Samuel GebÃ¼hr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Linkwarden settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - linkwarden_uid
    - linkwarden_gid
    - linkwarden_hostname
    - linkwarden_path_prefix
    - linkwarden_container_network
    - linkwarden_database_hostname
    - linkwarden_database_password
    - linkwarden_environment_variables_nextauth_secret

- name: Run if Traefik is enabled
  when: linkwarden_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Linkwarden are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - linkwarden_container_labels_traefik_hostname
        - linkwarden_container_labels_traefik_path_prefix

    - name: Fail if linkwarden_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          linkwarden_container_labels_traefik_path_prefix (`{{ linkwarden_container_labels_traefik_path_prefix }}`) must be `/`.
          Linkwarden does not support hosting under a subpath yet.
      when: "linkwarden_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `linkwarden_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if linkwarden_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          linkwarden_container_labels_traefik_path_prefix (`{{ linkwarden_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/linkwarden`).
      when: "linkwarden_container_labels_traefik_path_prefix != '/' and linkwarden_container_labels_traefik_path_prefix[-1] == '/'"
